---
title: "03_Manuscript_Figure_3_KappaVelo_velocity"
author: "Tim Kempchen"
date: '2022-12-08'
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: tango
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

Built with R version `{r} getRversion()`

## Setup {.tabset}

### Environment

```{r setup, message = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,  
  eval = TRUE, 
  tidy = TRUE
)

knitr::opts_knit$set(
  root.dir = "../"
)

# Environment Set up
rm(list = ls()) #Clean workspace
cat("\014")     #Clean Console
gc() # Free memory


# Establish working directory
library("rstudioapi")

# Set working directory to source file location
setwd(dirname(getActiveDocumentContext()$path))
setwd("..")

# Create output directories & load custom functions & colour scheme
source("scripts/Setup.R", local = knitr::knit_global())

# pipeline variables
long.compute <- FALSE

```

### Reading data

```{r reading_data}
# Read in CD8 only dataset
CD8.seurat <- LoadH5Seurat("saves/CD8_seurat.h5Seurat")
Idents(CD8.seurat) <- CD8.seurat@meta.data$Clusters_l1
DefaultAssay(CD8.seurat) <- "RNA"
```

### Subset Seurat object

```{r}
CD8.seurat <- subset(x = CD8.seurat, idents = c('Type_I_IFN','Cytotoxic', 'Stimulated_1'))
```

### Loading R packages

```{r}
library(Seurat)
library(tidyverse)
require(ggplot2)
```

## Prepare datasets for velocity {.tabset}

### Subset dataset by condition

```{r}

head(CD8.seurat@meta.data)

# untreated dataset
US.CD8.seurat <- subset(CD8.seurat, 
                        subset = condition %in% c("US"))

DimPlot(US.CD8.seurat,
        reduction = "umap") +
  ggtitle("untreated cells")

# treated dataset
Stim.CD8.seurat <- subset(CD8.seurat,
                          subset = condition %in% c("Stim"))

DimPlot(Stim.CD8.seurat, 
        reduction = "umap") +
  ggtitle("stimulated cells")


```

### Export information for velocity analysis

```{r}

output.dir <- "results/Manuscript/Figure3/whole_dataset/"

if(!dir.exists(paste0(output.dir))){
  dir.create(paste0(output.dir), 
             recursive = T)
}



write.csv(Cells(CD8.seurat), 
          file = paste0(output.dir, "cellID_obs.csv"), row.names = FALSE)

write.csv(Embeddings(CD8.seurat, reduction = "umap"), file = paste0(output.dir, "cell_embeddings.csv"))

write.csv(paste0("Cluster_",CD8.seurat@meta.data$Clusters_l1), file = paste0(output.dir, "clusters.csv"))


# untreated

output.dir.us <- "results/Manuscript/Figure3/US/"

if(!dir.exists(paste0(output.dir.us))){
  dir.create(paste0(output.dir.us), 
             recursive = T)
}


write.csv(Cells(US.CD8.seurat), 
          file = paste0(output.dir.us, "cellID_obs.csv"), row.names = FALSE)

write.csv(Embeddings(US.CD8.seurat, reduction = "umap"), file = paste0(output.dir.us, "cell_embeddings.csv"))

write.csv(paste0("Cluster_",US.CD8.seurat@meta.data$Clusters_l1), file = paste0(output.dir.us, "clusters.csv"))



# stimulated

output.dir.stim <- "results/Manuscript/Figure3/Stimulated/"

if(!dir.exists(paste0(output.dir.stim))){
  dir.create(paste0(output.dir.stim), 
             recursive = T)
}


write.csv(Cells(Stim.CD8.seurat), 
          file = paste0(output.dir.stim, "cellID_obs.csv"), row.names = FALSE)

write.csv(Embeddings(Stim.CD8.seurat, reduction = "umap"), file = paste0(output.dir.stim, "cell_embeddings.csv"))

write.csv(paste0("Cluster_",Stim.CD8.seurat@meta.data$Clusters_l1), file = paste0(output.dir.stim, "clusters.csv"))

```

