name: 2021_bald_velocyto
channels:
  - bioconda
  - conda-forge
dependencies:
  - numpy
  - scipy
  - cython
  - numba
  - matplotlib
  - scikit-learn
  - h5py
  - click
  - velocyto.py
