---
title: "HNSCC_scRNAseq_GO_Cytotrace_Augur"
author: "Dillon Corvino"
date: "03/02/2020"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: tango
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

Built with R version `{r} getRversion()`

## Setup {.tabset}

### Environment

```{r setup, message = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,  
  eval = TRUE, 
  tidy = TRUE
)

knitr::opts_knit$set(
  root.dir = "../"
)

# Environment Set up
rm(list = ls()) #Clean workspace
cat("\014")     #Clean Console
gc() # Free memory


# Establish working directory
library("rstudioapi")

# Set working directory to source file location
#setwd(dirname(getActiveDocumentContext()$path))
setwd("..")

# Load packages
source("R/Load_packages.R", local = knitr::knit_global())

# Create output directories & load custom functions & colour scheme
source("R/Setup.R", local = knitr::knit_global())


# pipeline variables
quick.load <- TRUE
long.compute <- TRUE

# load saved seurat object with cluster annotations and imputation performed
if(quick.load){
  seurat.combined <- readRDS("Exported_RDS_files/seurat_combined.rds")
}


```


## GSEA analysis {.tabset}

### Scillus

```{r Scillus_GSEA}

source("R/Analysis/Scillus_GO_analysis.R", local = knitr::knit_global())

```


## Additional analysis {.tabset}

### Cell Cycle & CytoTrace & Augur analysis

```{r Additional_analysis}

if(long.compute){
  source("R/Analysis/CellCycle_analysis.R", local = knitr::knit_global())
  source("R/Analysis/CytoTrace_analysis.R", local = knitr::knit_global())
  source("R/Analysis/Augur_analysis.R", local = knitr::knit_global())
}
```


