---
title: "02_Manuscript_Figure_2"
author: "Dillon Corvino"
date: "07/03/2022"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: tango
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

Built with R version `{r} getRversion()`

## Setup {.tabset}

### Dataset information

```{r Dataset_Info}

# HNSCC scRNAseq/scTCRseq dataset
# Cells are HNSCC TILs sorted on Lymphocytes/Live/CD3+/CD4-/CD8+
# Human samples
# Each sample is a pool of 4 patients
# samples 1 and 2 are unstimulated 
# samples 3 and 4 are stimulated 
# Patients in sample 1 match patients in sample 3 and sample 2 pairs with 4
# Data acquired was transcript expression, ADT (antibody expression), and TCRA & B sequences
# This analysis uses just Transcript and TCR data


# General information
# CellRanger was used for sequence alignment/QC/counts/TCR calls - performed by Ross (QIMR, Brisbane, Aus)
# DC was provided the output from CellRanger (counts matrix) and used this as input for analysis within this script

```

### Environment

```{r setup, message = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,  
  eval = TRUE, 
  tidy = TRUE
)

knitr::opts_knit$set(
  root.dir = "../"
)

# Environment Set up
rm(list = ls()) #Clean workspace
cat("\014")     #Clean Console
gc() # Free memory


# Establish working directory
library("rstudioapi")

# Set working directory to source file location
setwd(dirname(getActiveDocumentContext()$path))
setwd("..")

# Create output directories & load custom functions & colour scheme
source("scripts/Setup.R", local = knitr::knit_global())

# pipeline variables
long.compute <- FALSE



```


### Reading data

```{r reading_data}

########################
# Load all datasets 
########################

# CD8 dataset

CD8.seurat <- LoadH5Seurat("saves/CD8_seurat.h5Seurat")

Idents(CD8.seurat) <- CD8.seurat@meta.data$Clusters_l1
DefaultAssay(CD8.seurat) <- "RNA"

# CD8 TCR data

# TCR with no minimum clonotype filter
CD8.seurat.tcr <- LoadH5Seurat("saves/CD8_seurat_tcr.h5Seurat")

Idents(CD8.seurat.tcr) <- CD8.seurat.tcr@meta.data$Clusters_l1
DefaultAssay(CD8.seurat.tcr) <- "RNA"

# TCR data with a minimum clonotype filter
CD8.seurat.tcr.filt <- LoadH5Seurat("saves/CD8_seurat_tcr_filt.h5Seurat")

Idents(CD8.seurat.tcr.filt) <- CD8.seurat.tcr.filt@meta.data$Clusters_l1
DefaultAssay(CD8.seurat.tcr.filt) <- "RNA"

```






## Figure 2 Stimulation effect {.tabset}


### Set up for fig 2 output
```{r Fig_2_output}

# Create output directory

output.dir <- "results/Manuscript/Figure2/"


if(!dir.exists(paste0(output.dir))){
  dir.create(paste0(output.dir), 
             recursive = T)
}



```




### Visualise CD8 only UMAP
```{r vis_CD8_UMAP}

library(ggplot2)

UMAPPlot(object = CD8.seurat,
         group.by = "Clusters_l1",
         label = TRUE, 
         cols = CD8.cols,
         pt.size = 1,
         label.size = 6)  + NoLegend()

dev.copy(pdf, paste0(output.dir, "UMAP_CD8_clusters.pdf"))
dev.off()



Idents(CD8.seurat) <- CD8.seurat@meta.data$condition
US.seurat <- subset(CD8.seurat, ident = "US")
Stim.seurat <- subset(CD8.seurat, ident = "Stim")

UMAPPlot(object = US.seurat,
         group.by = "Clusters_l1",
         label = TRUE, 
         cols = CD8.cols,
         pt.size = 1,
         label.size = 6)  +
    ggtitle("Unstimulated") + 
  NoLegend()


dev.copy(pdf, paste0(output.dir, "UMAP_CD8_clusters_Unstimulated.pdf"))
dev.off()


UMAPPlot(object = Stim.seurat,
         group.by = "Clusters_l1",
         label = TRUE, 
         cols = CD8.cols,
         pt.size = 1,
         label.size = 6)  + 
  ggtitle("Stimulated") + 
  NoLegend()

dev.copy(pdf, paste0(output.dir, "UMAP_CD8_clusters_Stimulated.pdf"))
dev.off()



UMAPPlot(object = CD8.seurat,
         group.by = "Clusters_l1",
         split.by = "condition",
         cols = CD8.cols,
         pt.size = 1,
         label = TRUE, 
         label.size = 6) + NoLegend()

dev.copy(pdf, paste0(output.dir, "UMAP_CD8_clusters_named_condition_split.pdf"))
dev.off()





for(i in seq_along(condition.cols)){

  
  temp.cols <- c("Gray", "Gray")
  temp.cols[i] <- paste0(condition.cols)[i]

print(UMAPPlot(object = CD8.seurat,
         group.by = "condition",
         cols = temp.cols,
         pt.size = 1,
         shuffle = T,
         label = TRUE, 
         label.size = 6) + 
    NoLegend())

dev.copy(pdf, paste0(output.dir, "UMAP_CD8_clusters_", names(condition.cols[i]), "_coloured.pdf"))
dev.off()

}


UMAPPlot(object = CD8.seurat,
         group.by = "condition",
         cols = temp.cols,
         pt.size = 1,
         shuffle = T,
         label = TRUE, 
         label.size = 6) + 
    NoLegend()
dev.copy(pdf, paste0(output.dir, "UMAP_CD8_condition_combined_coloured.pdf"))
dev.off()

temp.cols <- condition.cols
names(temp.cols)[2] <-  "Stim"
temp.cols[2] <- "#ee8262"


library(RColorBrewer)


```



### Calculate DEGs without innate clusters
```{r DEG_calculation}

if(long.compute){
# Run DEG analysis
DEG.markers <- FindAllMarkers(CD8.seurat, 
                              slot = "data", 
                              logfc.threshold = 0.25,
                              test.use = "wilcox",
                              only.pos = FALSE)

# Filter for significance
DEG.markers <- 
  DEG.markers %>%
  filter(p_val_adj < 0.05)


write.csv(DEG.markers, paste0(output.dir, "DEG_CD8_Clusters_only.csv"))
}

```


 
### Annotated_heatmaps

```{r annotated_heatmap}


##################################################################
# Use complexheatmap to generate a manuscript ready figure
##################################################################

# Source custom function // loaded in custom functions chunk 
source("scripts/functions/annotate_seurat_heatmap_function.R")


# Make small seurat object for heatmap plotting
Idents(CD8.seurat) <- CD8.seurat@meta.data$Clusters_l1
small.seurat <- subset(CD8.seurat, downsample = 100)
small.seurat <- ScaleData(small.seurat)



# Ensure markers table is loaded
DEG.markers <- read.csv(paste0(output.dir, "DEG_CD8_Clusters_only.csv"))


# Get top cluster markers
genes.stim <- DEG.markers %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(avg_log2FC > 1) %>%
  dplyr::filter(cluster == "Stimulated_1") %>% 
  dplyr::pull(gene)


genes.exh <- DEG.markers %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(avg_log2FC > 1) %>%
  dplyr::filter(cluster == "Stimulated_exhausted") %>% 
  dplyr::pull(gene)


genes.to.plot <- unique(c(genes.stim, genes.exh))





DoHeatmap(small.seurat, genes.to.plot)



# Genes to be labeled if present in plotted heatmap
goi <- c("XCL1", "XCL2", "TNF", "TNFRSF9", "CRTAM", "IL2", "CD69", "TIGIT", "GZMB", "LAG3", "HAVCR2", "NKG7", "CTLA4", "GNLY", "CD226", "IFNG")


#install.packages("magick")

pdf(paste0(output.dir, "DEG_CD8_Clusters_only_annotated_sig_Stim_clusts.pdf"))
# Plot heatmap averaged values
annotated.heatmap(small.seurat, 
                  cluster.id = "Clusters_l1",
                  assay.use = "RNA",
                  average.expression = FALSE,
                  goi = genes.to.plot, 
                  genes.to.label = goi, 
                  col_order = names(CD8.cols), 
                  col.colours = CD8.cols, 
                  range.val = c(-2, 0, 2))

dev.off()




# Get top cluster markers
genes.to.plot <- DEG.markers %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::group_by(cluster) %>%
  dplyr::top_n(50, avg_log2FC) %>% 
  dplyr::pull(gene)


genes.to.plot <- unique(genes.to.plot)



# Genes to be labeled if present in plotted heatmap
goi <- c("ISG15", "IL7R", "GZMK", "MKI67", "XCL2", "HAVCR2", "LTB", "JUNB", "NKG7", "PRF1", "CCR7", "IFNG")


#install.packages("magick")

pdf(paste0(output.dir, "DEG_CD8_Clusters_only_annotated.pdf"))
# Plot heatmap averaged values
annotated.heatmap(CD8.seurat, 
                  cluster.id = "Clusters_l1",
                  assay.use = "RNA",
                  average.expression = TRUE,
                  goi = genes.to.plot, 
                  genes.to.label = goi, 
                  col_order = names(CD8.cols), 
                  col.colours = CD8.cols, 
                  range.val = c(-2, 0, 2))

dev.off()



# IFN Signature 



# Get top cluster markers
genes.to.plot <- DEG.markers %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(cluster == "Type_I_IFN") %>%
    dplyr::filter(avg_log2FC > 1) %>%
  dplyr::pull(gene)


genes.to.plot <- unique(genes.to.plot)



# Genes to be labeled if present in plotted heatmap
goi <- c("IFI6", "ISG20", "IFIT1", "OAS1", "IFIT2", "IRF7", "OAS2", "IFI35", "GZMK")



pdf(paste0(output.dir, "DEG_CD8_Clusters_only_annotated_IFNsig.pdf"))

# Plot heatmap averaged values
annotated.heatmap(CD8.seurat, 
                  cluster.id = "Clusters_l1",
                  assay.use = "RNA",
                  average.expression = FALSE,
                  goi = genes.to.plot, 
                  genes.to.label = goi, 
                  col_order = names(CD8.cols), 
                  col.colours = CD8.cols, 
                  range.val = c(-2, 0, 2))

dev.off()


```




### Distribution of cells across stimulation condition
```{r stim_condition_distribution}

# Get basic stats on cells per cluster and per condition and plot these values 

cells.conditon.clust <- table(CD8.seurat@meta.data$condition, CD8.seurat@meta.data$Clusters_l1)

# remove innate cluster columns 
pattern.val <- c("^gd_T_.*", "^MAIT$")
remove.logic <- grepl(paste0(pattern.val, collapse = "|"), colnames(cells.conditon.clust))
cells.conditon.clust <- cells.conditon.clust[ , !remove.logic]



cells.cluster <- colSums(cells.conditon.clust)


output.df <- cells.conditon.clust*NA

for(i in 1:length(cells.cluster)){
output.df[,i] <- (cells.conditon.clust[,i]/cells.cluster[i]) * 100
}


colSums(output.df)

# Plot freq of sample per cluster
barplot(output.df, 
        las = 2,
        col = condition.cols, 
        cex.names = 0.4)

dev.copy(pdf, paste0(output.dir, "Freq_of_condition_per_cluster.pdf"))
dev.off()




```





### CD8 seurat TCR data analysis
```{r CD8_TCR_analysis}

# Key questions
# Why do some cells move between clusters after stimulation 
# TCR recogniton between stim_1 and Stim_exhausted, is one bystander and the other tumor-specific, what is the clonal overlap between populations 


#install.packages("ggraph")
library(ggraph)

#devtools::install_github("ncborcherding/scRepertoire@dev")
library("scRepertoire")




# Show the distribution of clonotypes 

Idents(CD8.seurat.tcr) <- CD8.seurat.tcr@meta.data$cloneType

clonetypes <- levels(Idents(CD8.seurat.tcr))
clonotype.names <- c("Hyperexpanded", "Large", "Medium", "Small", "Single")




for(i in seq_along(clonetypes)){
  print(scCustomize::Cluster_Highlight_Plot(CD8.seurat.tcr, 
                                            cluster_name = paste0(clonetypes[i]), 
                                            highlight_color = "navy",
                                            background_color = "lightgray",
                                            split.by = "condition",
                                            pt.size = 1) + 
          NoLegend() + 
          ggtitle(paste0(clonetypes[i])))
  
  dev.copy(pdf, paste0(output.dir, "UMAP_highlighted_clonotype_", clonotype.names[i], "_split_condition.pdf"))
  dev.off()
}








# use .filt dataset which has single clonetypes removed


# subset data
Idents(CD8.seurat.tcr.filt) <- CD8.seurat.tcr.filt@meta.data$condition
US.seurat <- subset(CD8.seurat.tcr.filt, idents = "US")
Stim.seurat <- subset(CD8.seurat.tcr.filt, idents = "Stim")

# Reset Idents for plotting
Idents(CD8.seurat.tcr.filt) <- CD8.seurat.tcr.filt@meta.data$Clusters_l1
Idents(US.seurat) <- US.seurat@meta.data$Clusters_l1
Idents(Stim.seurat) <- Stim.seurat@meta.data$Clusters_l1


# First show the clonal overlap between clusters 
clonalOverlap(US.seurat, 
              cloneCall = "aa",
              chain = "both",
              method = "overlap")

dev.copy(pdf, paste0(output.dir, "Clonal_overlap_US_only.pdf"))
dev.off()

clonalOverlap(Stim.seurat,
              cloneCall = "aa",
              chain = "both",
              method = "overlap")

dev.copy(pdf, paste0(output.dir, "Clonal_overlap_Stim_only.pdf"))
dev.off()

clonalOverlap(CD8.seurat.tcr.filt,
              cloneCall = "aa",
              chain = "both",
              method = "overlap")

dev.copy(pdf, paste0(output.dir, "Clonal_overlap.pdf"))
dev.off()






# Plot bargraph of clonetype frequency per cluster

Idents(CD8.seurat.tcr) <- CD8.seurat.tcr@meta.data$cloneType

cells.clonetype.per.clust<- table(CD8.seurat.tcr@meta.data$cloneType, CD8.seurat.tcr@meta.data$Clusters_l1)

cells.cluster <- colSums(cells.clonetype.per.clust)

output.df <- cells.clonetype.per.clust*NA

for(i in 1:length(cells.cluster)){
output.df[,i] <- (cells.clonetype.per.clust[,i]/cells.cluster[i]) * 100
}


colSums(output.df)

clonetype.cols <- c("salmon4", "salmon", "orange", "cyan3", "Lightblue")
names(clonetype.cols) <- c("Hyperexpanded", "Large", "Medium", "Small", "Single")



# Plot freq of sample per cluster
barplot(output.df, 
        las = 2,
        legend = T,
        col = clonetype.cols, 
        cex.names = 0.5)

dev.copy(pdf, paste0(output.dir, "Freq_of_clonetype_per_cluster.pdf"))
dev.off()



# Overview of clonotype overlap 

UMAPPlot(CD8.seurat.tcr, 
         group.by = "Clonotype_overlap")


Idents(CD8.seurat.tcr) <- CD8.seurat.tcr@meta.data$Clonotype_overlap

overlap.status <- levels(Idents(CD8.seurat.tcr))



for(i in seq_along(overlap.status)){
  print(scCustomize::Cluster_Highlight_Plot(CD8.seurat.tcr, 
                                            cluster_name = paste0(overlap.status[i]), 
                                            highlight_color = "navy",
                                            background_color = "lightgray",
                                            pt.size = 1) + 
          NoLegend() + 
          ggtitle(paste0(overlap.status[i])))
  
  dev.copy(pdf, paste0(output.dir, "UMAP_highlighted_clonotype_", overlap.status[i], ".pdf"))
  dev.off()
}











# subset data for shared clonotypes only
Idents(CD8.seurat.tcr) <- CD8.seurat.tcr@meta.data$Clonotype_overlap
temp.seurat <- subset(CD8.seurat.tcr, idents = "Shared")
Idents(temp.seurat) <- temp.seurat@meta.data$Clusters_l1


scRepertoire::clonalNetwork(temp.seurat, 
                                    reduction = "umap", 
                                    identity = "Clusters_l1",
                                    filter.proportion = 0.05,
                                    filter.identity = "Stimulated_1",
                                    cloneCall = "aa") + ggtitle("Shared clonetypes")

dev.copy(pdf, "temp.pdf")
dev.off()




























seurat.list <- expression2List(CD8.seurat.tcr.filt, split.by = "Clusters_l1")


clonalProportion(seurat.list,
                 split = split.var,
                 cloneCall = "aa") 


clonalHomeostasis(tcr.clusters, 
                  cloneType = homeostasis.var,
                  cloneCall = "aa") + 
  theme(axis.text.x = element_text(angle = 90))



# for clonalProportion split
split.var <- c(1, 5, 10, 20, 50, 500, 5000, 1e+05)

# for clonalHomeostasis split
homeostasis.var <- c(Rare = 0.001, 
                     very_small = 0.002,
                     Small = 0.005, 
                     Medium = 0.01, 
                     Large = 0.05, 
                     very_Large = 0.1, 
                     Hyperexpanded = 1)






UMAPPlot(object = CD8.seurat.tcr,
         group.by = "Clusters_l1",
         label = TRUE, 
         cols = CD8.cols,
         pt.size = 1,
         label.size = 6)  + NoLegend()








# visualise clusters
p1 <- UMAPPlot(CD8.seurat.tcr, 
         group.by = "Clusters_l1",
         label = T) + NoLegend() + ggtitle("")

# clusters to plot
clust.ids <- as.character(unique(CD8.seurat.tcr@meta.data$Clusters_l1))

# plot all clusters
for(i in seq_along(clust.ids)){

  p2 <- scRepertoire::clonalNetwork(US.seurat, 
                                    reduction = "umap", 
                                    identity = "Clusters_l1",
                                    filter.proportion = 0.01,
                                    filter.identity = clust.ids[i],
                                    cloneCall = "aa") + ggtitle("US")
  
  p3 <- scRepertoire::clonalNetwork(Stim.seurat, 
                                    reduction = "umap", 
                                    identity = "Clusters_l1",
                                    filter.proportion = 0.01,
                                    filter.identity = clust.ids[i],
                                    cloneCall = "aa") + ggtitle("Stim")
  

  print(p1 + p2/p3)
  
 #ggsave(paste0(output.dir, "output_tcr/figures/clonalnetworks/ClonalNetwork_", clust.ids[i], ".pdf"))

  
}


clonalOverlay(CD8.seurat.tcr, reduction = "umap", 
              freq.cutpoint = 1) + 
                guides(color = "none")



scRepertoire::clonalNetwork(CD8.seurat.tcr, 
                                    reduction = "umap", 
                                    identity = "Clusters_l1",
                                    filter.proportion = 0.01,
                                    filter.identity = "Cytotoxic",
                                    cloneCall = "aa") + ggtitle("Stim")


scRepertoire::clonalNetwork(CD8.seurat.tcr, 
                                    reduction = "umap", 
                                    identity = "Clusters_l1",
                                    #filter.proportion = 0.01,
                                    filter.clones =  1,
                                    cloneCall = "aa") + ggtitle("Stim")



CD8.seurat.tcr@meta.data$cloneType

occupiedscRepertoire(CD8.seurat.tcr, x.axis = "Clusters_l1", proportion = T)

?occupiedscRepertoire
CD8.seurat.tcr@meta.data

temp.seurat <- clusterTCR(seurat.list,
                          chain = "TRB",
                          group.by = "group", 
                          sequence = "aa", 
                          threshold = 0.85)

DimPlot(seurat, group.by = "TRB_cluster") + 
  NoLegend()
?clusterTCR


head(CD8.seurat.tcr@meta.data)
StartracDiversity(CD8.seurat.tcr,
                  type = "condition", 
            sample = "group", by = "overall")




clonotypeBias(CD8.seurat.tcr, cloneCall = "aa", split.by = "group", group.by = "Clusters_l1",
n.boots = 20, min.expand =10)

### Misc code for exploring functions of scRep package

seurat.list <- expression2List(CD8.seurat.tcr, split.by = "Clusters_l1")
length(seurat.list) #now listed by cluster









scRepertoire::clonalNetwork(US.seurat, 
                                    reduction = "umap", 
                                    identity = "Clusters_l1",
                                    filter.proportion = 0.01,
                                    filter.identity = "Cytotoxic",
                                    cloneCall = "aa") + ggtitle("US")





```


### Heatmap of top clonotypes
```{r Heatmap_top_clonotypes}

library(gplots)
library(RColorBrewer)
########################
# Heatmap functions
########################

hclust.func <- function(x){
  hclust(x, method = 'ward.D2')
}

dist.func <- function(x){
  dist(x,method = 'binary')
}

col.palette <- colorRampPalette(brewer.pal(8, "RdYlBu"))(600)





# Get data of how many cells in each cluster are assigned to what clonotypes
clonotype.data <- table(CD8.seurat.tcr@meta.data$CTaa, CD8.seurat.tcr@meta.data$Clusters_l1)


# Plot the top 10 clonotypes
aa.keep <- sort(rowSums(clonotype.data), decreasing = TRUE)[1:50]

keep.vec <- rownames(clonotype.data) %in% names(aa.keep)

plot.data <- clonotype.data[keep.vec, ]


heatmap.2(as.matrix(log2(plot.data+1)), 
          scale = "none",
          trace = "none",
          ColSideColors = CD8.cols,
          Colv = TRUE,
          cexRow = 0.8, 
          margins = c(8, 15),
          cexCol = 0.8, 
          distfun = dist.func,
          hclustfun = hclust.func,
          srtCol = 90,
          col = rev(col.palette))     

dev.copy(pdf, paste0(output.dir, "Heatmap_top_50_clonotypes.pdf"))
dev.off()







############################################
# Plot top clonotypes in each cluster 
############################################

for(i in seq_along(colnames(clonotype.data))){
  temp <- as.data.frame(clonotype.data)
  
  temp <- temp %>%
    dplyr::filter(Var2 == paste0(colnames(clonotype.data)[i])) %>%
    dplyr::top_n(10)
  
  clonotypes.to.plot <- temp$Var1
  
  keep.vec <- rownames(clonotype.data) %in% clonotypes.to.plot
  
  plot.data <- clonotype.data[keep.vec, ]
  
  heatmap.2(as.matrix(log2(plot.data+1)), 
            scale = "none",
            trace = "none",
            ColSideColors = CD8.cols,
            Colv = FALSE,
            cexRow = 0.8, 
            margins = c(8, 15),
            cexCol = 0.8, 
            distfun = dist.func,
            hclustfun = hclust.func,
            srtCol = 90,
            col = rev(col.palette))
  
  dev.copy(pdf, paste0(output.dir, "Heatmap_top_10_clonotypes_in_", colnames(clonotype.data)[i], ".pdf"))
  dev.off()
  
}




```











