---
title: "03_Manuscript_Figure_2"
author: "Dillon Corvino"
date: "07/03/2022"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: tango
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

Built with R version `{r} getRversion()`

## Setup {.tabset}


### Environment

```{r setup, message = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,  
  eval = TRUE, 
  tidy = TRUE
)

knitr::opts_knit$set(
  root.dir = "../"
)

# Environment Set up
rm(list = ls()) #Clean workspace
cat("\014")     #Clean Console
gc() # Free memory


# Establish working directory
library("rstudioapi")

# Set working directory to source file location
setwd(dirname(getActiveDocumentContext()$path))
setwd("..")

# Create output directories & load custom functions & colour scheme
source("scripts/Setup.R", local = knitr::knit_global())

# pipeline variables
long.compute <- FALSE

# load required packages
require(tidyverse)
require(Seurat)
library(ggplot2)



# Create output directory
output.dir <- "results/Manuscript/Figure2/"

if(!dir.exists(paste0(output.dir))){
  dir.create(paste0(output.dir), 
             recursive = T)
}

```




### Reading data

```{r reading_data}

########################
# Load dataset
########################

# CD8 dataset
CD8.seurat <- LoadH5Seurat("saves/CD8_seurat.h5Seurat")

Idents(CD8.seurat) <- CD8.seurat@meta.data$Clusters_l1
DefaultAssay(CD8.seurat) <- "RNA"


```


## Figure 2 {.tabset}

### Figure 2A & B
```{r Figure_2A_B}

# Figure 2A
UMAPPlot(object = CD8.seurat,
         group.by = "Clusters_l1",
         label = TRUE, 
         cols = CD8.cols,
         pt.size = 1,
         label.size = 6)  + 
  NoLegend()

dev.copy(pdf, paste0(output.dir, "Figure_2A.pdf"))
dev.off()

```



### Figure 2B
```{r Figure_2B}

if(long.compute){
  
  Idents(CD8.seurat) <- CD8.seurat@meta.data$Clusters_l1
  DefaultAssay(CD8.seurat) <- "RNA"
  
  # Run DEG analysis
  DEG.markers <- FindAllMarkers(CD8.seurat, 
                                slot = "data", 
                                logfc.threshold = 0.25,
                                test.use = "wilcox",
                                only.pos = FALSE)
  
  # Filter for significance
  DEG.markers <- 
    DEG.markers %>%
    filter(p_val_adj < 0.05)
  
  
  write.csv(DEG.markers, paste0(output.dir, "Figure_2B_DEGs.csv"))
}


# load data
DEG.wilcox <- read.csv(paste0(output.dir, "Figure_2B_DEGs.csv"))
DEG.wilcox <- DEG.wilcox[,-1]


# prepare dataset
Idents(CD8.seurat) <- CD8.seurat@meta.data$Clusters_l1
DefaultAssay(CD8.seurat) <- "RNA"


# Average dataset
average.seurat <- AverageExpression(CD8.seurat, return.seurat = TRUE)


# Top DEGs

# DEGs > 0.5 log2FC
goi <- DEG.wilcox %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::filter(cluster == "Stimulated_1" | cluster == "Stimulated_exhausted") %>%
  dplyr::filter(avg_log2FC > 0.5)

goi <- goi$gene[duplicated(goi$gene)]


source("scripts/functions/annotate_seurat_heatmap_function.R")


label.var <- unique(c("IFNG", "GZMB", "TNFRSF9", "FASLG", "CRTAM", "VSIR", "ICOS", "CD48"))

goi <- sample(goi)

pdf(paste0(output.dir, "Figure_2B.pdf"))

# Plot heatmap
annotated.heatmap(CD8.seurat, 
                  cluster.id = "Clusters_l1",
                  assay.use = "RNA",
                  average.expression = TRUE,
                  goi = goi, 
                  genes.to.label = label.var, 
                  col_order = names(CD8.cols), 
                  col.colours = CD8.cols)

dev.off()


```


### Figure 2C
```{r Figure_2C}


Idents(CD8.seurat) <- CD8.seurat@meta.data$Clusters_l1
DefaultAssay(CD8.seurat) <- "RNA"


if(long.compute){

  # Run DEG analysis
  DEG.markers <- FindMarkers(CD8.seurat, 
                             ident.1 = "Stimulated_1",
                             ident.2 = "Stimulated_exhausted",
                             slot = "data", 
                             logfc.threshold = 0.25,
                             test.use = "wilcox",
                             only.pos = FALSE)
  
# Filter for significance
DEG.markers <- 
  DEG.markers %>%
  filter(p_val_adj < 0.05)


write.csv(DEG.markers, paste0(output.dir, "Figure_2C_DEGs.csv"))
}


# read in dataset
DEG.markers <- read.csv(paste0(output.dir, "Figure_2C_DEGs.csv"))


goi <- DEG.markers %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  dplyr::mutate(abs.log = abs(avg_log2FC)) %>%
  dplyr::filter(abs.log > 0.5) %>%
  dplyr::arrange(desc(avg_log2FC))


goi <- unique(goi$X)

label.var <- unique(c("IL7R", "XCL1", "TAGLN2", "TNF", "CD69", "CCR7", "TNFSF14", "GZMK", "LTB", "CD28", "TCF7", "ISG20", "CD28", "TOX", "CD96", "TNFSF10", "HAVCR2", "GNLY", "LAG3", "TIGIT", "ENTPD1", "KLRC1", "CD226", "GZMA"))



pdf(paste0(output.dir, "Figure_2C.pdf"))

# Plot heatmap
annotated.heatmap(CD8.seurat, 
                  cluster.id = "Clusters_l1",
                  assay.use = "RNA",
                  average.expression = TRUE,
                  goi = goi, 
                  genes.to.label = label.var, 
                  col_order = names(CD8.cols), 
                  col.colours = CD8.cols)

dev.off()


```
 
 
 
 

 
 # up to here i have edited


### Sup figure ??
```{r TF_analysis_inference}

# Create output directory
output.dir <- "results/Manuscript/Figure2/TF_inference/"

if(!dir.exists(paste0(output.dir))){
  dir.create(paste0(output.dir), 
             recursive = T)
}



# install and load packages
#BiocManager::install("decoupleR") 
library("decoupleR")

# Retrieve prior knowledge network.
network <- decoupleR::get_dorothea(organism = "human",
                                   levels = c("A", "B", "C"))

# Run weighted means algorithm.
activities <- decoupleR::run_wmean(mat = as.matrix(CD8.seurat@assays$RNA@data),
                                   network = network,
                                   .source = "source",
                                   .targe = "target",
                                   .mor = "mor",
                                   times = 100,
                                   minsize = 5)

# General heatmap.
out <- SCpubr::do_TFActivityPlot(sample = CD8.seurat,
                                 cluster_rows = FALSE,
                                 flip = FALSE,
                                 activities = activities, 
                                 n_tfs = 50)
p <- out$heatmaps$average_scores
p

dev.copy(pdf, paste0(output.dir, "/Heatmap_of_TF_activity_top50.pdf"))
dev.off()

# load custom functions to interact with dorothea output 
source("scripts/functions/dorothea_functions.R")


# Add dorothea data to seurat object
CD8.seurat <- add.dorothea.data(CD8.seurat, activities)

# get a table of activity scores 
tf.data <- extract.top.TFs.dorothea(CD8.seurat, 
                         group.var = "Clusters_l1", 
                         return.table = TRUE,
                         n_tfs = 50)

# filter table for top transcription factors
goi <- tf.data %>%
  filter(mean > 1) %>%
  arrange(group.var, mean) %>%
  pull(source)

length(goi)

# Average seurat object
average.seurat <- AverageExpression(CD8.seurat, 
                                    return.seurat = TRUE)

# plot heatmap of top predicted transcripton factor activity scores
DoHeatmap(average.seurat, 
          group.colors = CD8.cols,
          features = goi, 
          raster = FALSE,
          draw.lines = FALSE) + 
  scico::scale_fill_scico(palette = "batlow", 
                          direction = 1, 
                          na.value = "white")


dev.copy(pdf, paste0(output.dir, "/Heatmap_of_TF_activity_top_predicted.pdf"))
dev.off()


```


 
 
 



