---
title: "06_Manuscript_Figure_5"
author: "Dillon Corvino"
date: "07/03/2022"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: tango
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

Built with R version `{r} getRversion()`

## Setup {.tabset}

### Environment

```{r setup, message = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,  
  eval = TRUE, 
  tidy = TRUE
)

knitr::opts_knit$set(
  root.dir = "../"
)

# Environment Set up
rm(list = ls()) #Clean workspace
cat("\014")     #Clean Console
gc() # Free memory


# Establish working directory
library("rstudioapi")

# Set working directory to source file location
setwd(dirname(getActiveDocumentContext()$path))
setwd("..")

# Create output directories & load custom functions & colour scheme
source("scripts/Setup.R", local = knitr::knit_global())

# pipeline variables
long.compute <- FALSE

# load required packages
require(tidyverse)
require(Seurat)
require(useful)
require(UCell)
require(Nebulosa)
library(harmony)

#source("scripts/aimed_analysis/functions.R")


# Create output directory
output.dir <- "results/Manuscript/Figure_5/"

if(!dir.exists(paste0(output.dir))){
  dir.create(paste0(output.dir), 
             recursive = TRUE)
}
```


## Figure 5 {.tabset}

### Prepare dataset / read and filter for CD8 / or load dataset

```{r read_dataset_pancancer}

if(long.compute){
  
  # Due to memory limits, the dataset is written in as pancancer.cd8 rather than subsetting for cd8 and creating a new variable. 
  #i.e use only one variable to limit the memory requirments 
pancancer.cd8 <- LoadH5Seurat("data/external_datasets/Utility_dataset.h5Seurat")

Idents(pancancer.cd8) <- pancancer.cd8@meta.data$functional.cluster
pancancer.cd8 <- subset(pancancer.cd8, idents = c("CD8_EffectorMemory", "CD8_NaiveLike", "CD8_EarlyActiv", "CD8_Tex", "CD8_Tpex"))

# still many cells of mixed annotation by consensus.major ID
Idents(pancancer.cd8) <- pancancer.cd8@meta.data$consensus.major
pancancer.cd8 <- subset(pancancer.cd8, idents = "T_cell")

# further filtering for CD8 T cell annotation
Idents(pancancer.cd8) <- pancancer.cd8@meta.data$consensus.Tcell
pancancer.cd8 <- subset(pancancer.cd8, idents = "CD8")

# further filtering for annotation
Idents(pancancer.cd8) <- pancancer.cd8@meta.data$HPCA.pruned.labels
keep.var <- grep(".*CD8.*", unique(Idents(pancancer.cd8)), value =T)

pancancer.cd8 <- subset(pancancer.cd8, idents = keep.var)

# Type annotation
table(pancancer.cd8@meta.data$Type)/1000
# Juxta = 262 cells only
# Blood = 12.993K
# LN = 23.25K
# Met = 5.711K
# Normal = 41.119K
# Tumor = 173.74K

# Therefore remove Juxta cells 
# also remove Met and LN as these are a bit complicated to include in analysise.
# i.e the biological interpretation of Met tissue is highly dependent on each manuscript and what they mean by met and if LN is healthy or diseased
# also remove blood to keep it simple, normal and tumor tissue


Idents(pancancer.cd8) <- pancancer.cd8@meta.data$Type
pancancer.cd8 <- subset(pancancer.cd8, idents = c("Tumor", "Normal"))


table(pancancer.cd8@meta.data$Type, pancancer.cd8@meta.data$Tissue)


library(harmony)
# Normalise and harmonize dataset and calculate umap projection
pancancer.cd8 <- 
  pancancer.cd8 %>%
  NormalizeData() %>%
  FindVariableFeatures() %>%
  ScaleData() %>%
  RunPCA() %>%
  harmony::RunHarmony(reduction = "pca",
                      group.by.vars = c("Cohort"), 
                      plot_convergence = TRUE, 
                      verbose = TRUE) %>%
  RunUMAP(reduction = "harmony", 
          dims = 1:20) %>%
  FindNeighbors(reduction = "harmony",
                dims = 1:20) %>%
  FindClusters(resolution = 0.5)


# save filtered dataset
SaveH5Seurat(pancancer.cd8, 
             "data/external_datasets/pancancer_cd8_normed.h5Seurat",
             overwrite = TRUE)


}else{
  
  pancancer.cd8 <- LoadH5Seurat("data/external_datasets/pancancer_cd8_normed.h5Seurat")

}

# quick visualisation of the normed and subseted CD8 dataset

UMAPPlot(pancancer.cd8, 
         group.by = "HPCA.pruned.labels")

UMAPPlot(pancancer.cd8,
         pt.size = 1,
         group.by = "seurat_clusters")



```
 
### apply ucell score to pancancer

```{r ucell_pancancer}

if(!exists("pancancer.cd8")){
  
    pancancer.cd8 <- LoadH5Seurat("data/external_datasets/pancancer_cd8_normed.h5Seurat")

}

if(long.compute){

 cores <- parallel::detectCores(all.tests = FALSE, logical = TRUE)

# Calculate Ucell scores for signatures
DefaultAssay(pancancer.cd8) <- "RNA"
pancancer.cd8 <- UCell::AddModuleScore_UCell(pancancer.cd8,
                                             features = Signature.list,
                                             ncores = cores)

# Export object with UCell score
SaveH5Seurat(pancancer.cd8, 
             "data/external_datasets/pancancer_cd8_normed.h5Seurat", 
             overwrite = TRUE)

}

```
 
 
### Figure 5A
```{r Figure_5A}

colnames(pancancer.cd8@meta.data)

# Visualise the results

# Density plots 
Plot_Density_Custom(pancancer.cd8, 
                    features =  "Top_10_UCell",
                    custom_palette = batlow.pal,
                    joint = FALSE, 
                    pt.size = 1, 
                    reduction = "umap")

dev.copy(pdf, paste0(output.dir, "Figure_5A.pdf"))
dev.off()


# subset dataset to enable figure creation as to many points 
Idents(pancancer.cd8) <- pancancer.cd8@meta.data$consensus.major
# 214,863 cells total dataset 
unique(Idents(pancancer.cd8))

temp.seurat <- subset(pancancer.cd8, downsample = 50000)

temp.seurat # 50,000 cells

# Density plots 
Plot_Density_Custom(temp.seurat, 
                    features =  "Top_10_UCell",
                    custom_palette = batlow.pal,
                    joint = FALSE, 
                    pt.size = 1, 
                    reduction = "umap")

dev.copy(pdf, paste0(output.dir, "Figure_5A_downsampled.pdf"))
dev.off()

rm(temp.seurat)



# Cluster distribution

# VlnPlots
VlnPlot(pancancer.cd8,
        pt.size = 0, 
        same.y.lims = T,
        features = "Top_10_UCell",
        group.by = "seurat_clusters") + 
  NoLegend()

#dev.copy(pdf, paste0(output.dir, "Pancancer_VlnPlot_UCell_scores_top10.pdf"))
#dev.off()



# Specifically colour IFN cluster
Idents(pancancer.cd8) <- pancancer.cd8@meta.data$seurat_clusters

scCustomize::Cluster_Highlight_Plot(pancancer.cd8, 
                                    cluster_name = "7", 
                                    highlight_color = "Red", 
                                    background_color = "lightgray", 
                                    pt.size = 0.1, 
                                    raster = TRUE)

#dev.copy(pdf, paste0(output.dir, "Pancancer_UMAP_clusters_highlighted.pdf"))
#dev.off()


# Cluster number 7 = IFN cluster


```
 
 
### Figure 5B & C
```{r Figure_5B_C}

# Which cluster is the IFN high cluster
IFN.cluster <- "7"


#################################################################################
# within sequenced cells from the tumor, which tumor has the most IFN cluster
#################################################################################

# filter for just tumor tissue derived cells
Idents(pancancer.cd8) <- pancancer.cd8@meta.data$Type

tumor.seurat <- subset(pancancer.cd8, idents = "Tumor")

Idents(tumor.seurat) <- tumor.seurat@meta.data$Tissue

tumor.seurat # 54,971 cells and 173,744 cells

 
# extract stats
tumor.by.cluster <- table(tumor.seurat@meta.data$Tissue, tumor.seurat@meta.data$seurat_clusters)

logic.vec <- grepl(paste0(IFN.cluster), colnames(tumor.by.cluster))
IFN.by.cluster <- tumor.by.cluster[, logic.vec]


cells.sequenced <- table(tumor.seurat@meta.data$Tissue)

cells.sequenced

IFN.freq <- (IFN.by.cluster/cells.sequenced)*100

max(IFN.freq)
IFN.freq <- sort(IFN.freq, decreasing = T)

barplot(IFN.freq, 
        las = 2,
        col = c("gray", "blue"), 
        cex.names = 0.6, 
        ylim = c(0, 25))

dev.copy(pdf, paste0(output.dir, "Figure_5B.pdf"))
dev.off()

# write data to file
write.csv(IFN.freq, paste0(output.dir, "Figure_5B.csv"))

# clean environment 
rm(tumor.seurat)
gc()



######################################################################################################
# Extract and calculate freq of IFN cluster across normal and disease in various tumor types
######################################################################################################

# select tumors that have both normal and disease 
table(pancancer.cd8@meta.data$Type, pancancer.cd8@meta.data$Tissue)

# subset for tumor type
Idents(pancancer.cd8) <- pancancer.cd8@meta.data$Tissue

tissue.vec <- c("Colorectal", "Endometrial", "Esophagus", "Lung", "Renal")


for(i in seq_along(tissue.vec)){
  
  # subset for tumor type
  temp.seurat <- subset(pancancer.cd8, idents = tissue.vec[i])
  
  # get number of sequenced cells
  sequenced.cell.num <- table(temp.seurat@meta.data$Type)
  
  # get values for number of cells in each cluster across normal or disease
  cluster.vals <- table(temp.seurat@meta.data$seurat_clusters, 
                        temp.seurat@meta.data$Type)
  
  # extract cell numbers for cluster 7 only
  IFN.clust.vals <- cluster.vals[grepl(paste0(IFN.cluster), rownames(cluster.vals)), ]
  
  # calculate the freq of normal or disease that is within the IFN cluster
  IFN.freq <- (IFN.clust.vals/sequenced.cell.num)*100
  
  # plot values
  barplot(IFN.freq, 
          las = 2,
          col = c("gray", "blue"), 
          cex.names = 0.6, 
          ylim = c(0, 25))
  
  dev.copy(pdf, paste0(output.dir, tissue.vec[i], "_Figure_5C_barplot_IFN_cluster_freq_across_disease_status.pdf"))
  dev.off()
  
  # write data to file
  write.csv(IFN.freq, paste0(output.dir, tissue.vec[i], "_Figure_5C_IFN_cluster_freq_across_disease_status.csv"))
  
  
  # freq of within IFN cluster 
  total.IFN <- sum(IFN.freq)
  
  normed.IFN <- (IFN.freq/total.IFN)*100
  
    barplot(normed.IFN, 
          las = 2,
          col = c("gray", "blue"), 
          cex.names = 0.6, 
          ylim = c(0, 100))
  
  dev.copy(pdf, paste0(output.dir, tissue.vec[i], "_barplot_freq_across_disease_status_within_IFN_cluster.pdf"))
  dev.off()
  
  # write data to file
  write.csv(normed.IFN, paste0(output.dir, tissue.vec[i], "_freq_within_IFN_cluster_across_disease_status.csv"))
  
  rm(temp.seurat)
  gc()
  
}


```


### reduce dataset to ISG high tumors (Ovarian, Esophagus, Breast)
```{r ISG_high_tumors}

if(long.compute){
  # Subset for ISG cluster enriched tumors
  Idents(pancancer.cd8) <- pancancer.cd8@meta.data$Tissue
  table(pancancer.cd8@meta.data$Tissue, pancancer.cd8@meta.data$Type)
  
  tissue.vec <- c("Ovarian", "Esophagus", "Breast")
  
  ISG.tumors.seurat <- subset(pancancer.cd8, idents = tissue.vec)
  
  # take just cells from tumor tissue
  Idents(ISG.tumors.seurat) <- ISG.tumors.seurat@meta.data$Type
  
  ISG.tumors.seurat <- subset(ISG.tumors.seurat, idents = "Tumor")
  
  # check subsetting correctly performed 
  table(ISG.tumors.seurat@meta.data$Tissue, ISG.tumors.seurat@meta.data$Type)

  
  library(harmony)
  # Normalise and harmonize dataset and calculate umap projection
  
  # store upper level seurat clusters incase needed later
  ISG.tumors.seurat$orig.clusters <- ISG.tumors.seurat@meta.data$seurat_clusters

  
  ISG.tumors.seurat <- 
    ISG.tumors.seurat %>%
    Seurat::NormalizeData() %>%
    Seurat::FindVariableFeatures() %>%
    Seurat::ScaleData() %>%
    Seurat::RunPCA() %>%
    harmony::RunHarmony(reduction = "pca",
                        group.by.vars = c("Cohort", "Sample"), 
                        plot_convergence = TRUE, 
                        verbose = TRUE)  %>%
    Seurat::RunUMAP(reduction = "harmony", 
          dims = 1:20, 
          min.dist = 0.3, 
          spread = 1,
          n.neighbors = 5, # 5 - 50 , larger = more global
          densmap = F,
          seed.use = 42)  %>%
  FindNeighbors(reduction = "harmony",
                dims = 1:20) %>%
  FindClusters(resolution = 0.5)

  
  # Rename clusters
ISG.tumors.seurat@meta.data$IFN_clusters <- ISG.tumors.seurat@meta.data$seurat_clusters

Idents(ISG.tumors.seurat) <- ISG.tumors.seurat@meta.data$IFN_clusters
ISG.tumors.seurat <- ISG.tumors.seurat %>%
  RenameIdents('0' = "other",
               '1' = "other",
               '2' = "other", 
               '3' = "other",
               '4' = "other", 
               '5' = "ISG", 
               '6' = "other", 
               '7' = "other",
               '8' = "other",
               '9' = "other",
               '10' = "other")
Idents(ISG.tumors.seurat)

ISG.tumors.seurat@meta.data$IFN_status <- Idents(ISG.tumors.seurat)

    # save normed and recalculated umap
  SaveH5Seurat(ISG.tumors.seurat, 
               "data/external_datasets/ISG_tumors_seurat.h5Seurat",
               overwrite = TRUE)
  
  
}else if(!exists("ISG.tumors.seurat")){
  
  ISG.tumors.seurat <- LoadH5Seurat("data/external_datasets/ISG_tumors_seurat.h5Seurat")
  
  
}

```
 
### Figure 5D
```{r Figure_5D}

##################################################################################################
# Vln plot of Ucell scores for T1 and T2 IFN calculated on original dataset by Nick Borcherding
##################################################################################################

VlnPlot(ISG.tumors.seurat,
        feature = "T1_Interferon_UCell",
        pt.size = 0,
        split.by = "Tissue",
        group.by = "IFN_status")

dev.copy(pdf, paste0(output.dir, "Figure_5D_T1_Ucell.pdf"))
dev.off()

VlnPlot(ISG.tumors.seurat,
        feature = "T2_Interferon_UCell",
        pt.size = 0,
        split.by = "Tissue",
        group.by = "IFN_status")

dev.copy(pdf, paste0(output.dir, "Figure_5D_T2_Ucell.pdf"))
dev.off()




```
 
 