---
title: "Trajectory Analysis"
author: "Lisa M. Steinheuer"
output: html_notebook
---

# Data analysis

## Preface

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
knitr::opts_chunk$set(fig.width = 10, fig.height = 4)
```

### Libraries

```{r libs_and_functions}
library(dplyr)
library(Seurat)
library(foreach)
#library(purrr)
library(ggplot2)
library(plyr)
library(magrittr)
library(reshape2)
library(RColorBrewer)
library(SeuratDisk)
library(monocle3)
library(SeuratWrappers)

#----------------------------------------------------
project <- 'HNSCC_Tra'
input <- "/mnt/share/home_steinheu//Data/HNSCC_dataset/input/"
rdata <- "/mnt/share/home_steinheu/Data/HNSCC_dataset/RData/"
results <- "/mnt/share/home_steinheu/Data/HNSCC_dataset/results/"
#----------------------------------------------------

#source("20221028_HelperFunctions.R")

get_earliest_principal_node <- function(cds, time_bin) {
  cell_ids <- which(colData(cds)[, "Clusters_l1"] == time_bin)

  closest_vertex <-
    cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex
  closest_vertex <- as.matrix(closest_vertex[colnames(cds),])
  root_pr_nodes <-
    igraph::V(principal_graph(cds)[["UMAP"]])$name[as.numeric(names
                                                              (which.max(table(closest_vertex[cell_ids,]))))]

  root_pr_nodes
}


theme_lisa <- function() {
  theme_minimal() %+replace%    #replace elements we want to change

    theme( #axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      text = element_text(size = 10)) +
    theme( #legend.position = "bottom",
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(colour = "black"),
      axis.text = element_text(
        size = 8),
      axis.title = element_text(size = 8),
      legend.title = element_text(size = 8),
      legend.text = element_text(size = 8),
      axis.text.x = element_text(size = 8),
      strip.text.x = element_text(size = 8))
}
```

```{r}
hnscc <- LoadH5Seurat(paste0(input, "CD8_seurat.h5Seurat"))
```

```{r}
head(hnscc@meta.data)
```

```{r}
stim_hnscc <- subset(hnscc, condition == "Stim")
reduced_stim <- subset(hnscc, Clusters_l1 %in% c("Exhausted_1", "Exhausted_2", "Proliferative", "Stimulated_exhausted", "TRM"), invert = TRUE)
```

```{r}
DefaultAssay(reduced_stim) <- 'RNA'
all.genes <- rownames(reduced_stim)
reduced_stim <- ScaleData(reduced_stim, features = all.genes)

DefaultAssay(reduced_stim) <- 'integrated'
reduced_stim <- FindVariableFeatures(reduced_stim, selection.method = "vst", nfeatures = 2000)

all.genes <- rownames(reduced_stim)
reduced_stim <- RunPCA(reduced_stim, features = VariableFeatures(object = reduced_stim))
ElbowPlot(reduced_stim, ndims = 40)
reduced_stim <- FindNeighbors(reduced_stim, dims = 1:20)
reduced_stim <- FindClusters(reduced_stim, resolution = 0.8)
reduced_stim <- RunUMAP(reduced_stim, dims = 1:10)
reduced_stim <- FindClusters(reduced_stim)
```
```{r fig.width = 5}
DimPlot(reduced_stim, reduction = "umap", group.by = "Clusters_l1")
```

```{r}
cds <- as.cell_data_set(reduced_stim)

# to get cell metadata
colData(cds)
# to gene metdata
fData(cds)
rownames(fData(cds))[1:10]

# since it misses the gene_short_name column, let's add it
fData(cds)$gene_short_name <- rownames(fData(cds))

# ...2. Cluster cells (using clustering info from seurat's UMAP)---------------------------
# let's use the clustering information have

# assign paritions
reacreate.partition <- c(rep(1, length(cds@colData@rownames)))
names(reacreate.partition) <- cds@colData@rownames
reacreate.partition <- as.factor(reacreate.partition)


cds@clusters$UMAP$partitions <- reacreate.partition

# Assign the cluster info

list_cluster <- reduced_stim@active.ident
cds@clusters$UMAP$clusters <- list_cluster


# Assign UMAP coordinate - cell embeddings

cds@int_colData@listData$reducedDims$UMAP <- reduced_stim@reductions$umap@cell.embeddings



# plot

cluster.before.trajectory <- plot_cells(cds,
                                        color_cells_by = 'cluster',
                                        label_groups_by_cluster = FALSE,
                                        group_label_size = 5) +
  theme(legend.position = "right")

cluster.names <- plot_cells(cds,
                            color_cells_by = "Clusters_l1",
                            label_groups_by_cluster = FALSE,
                            label_cell_groups = FALSE,
                            group_label_size = 5) +
  scale_color_manual(values = c('red', 'blue', 'green', 'maroon', 'yellow', 'cyan')) +
  theme(legend.position = "right", legend.key.size = unit(0.25, 'cm')) +
  theme_lisa()

ggsave(filename = paste0("~/Desktop/Trajectory_stim_reduced.pdf"), plot = cluster.names, width = 3.5, height = 2)

cluster.before.trajectory | cluster.names

```
```{r}
# ...3. Learn trajectory graph ------------------------
cds <- learn_graph(cds, use_partition = FALSE)

p1 <- plot_cells(cds,
           color_cells_by = 'Clusters_l1',
           label_groups_by_cluster = FALSE,
           label_branch_points = FALSE,
           label_roots = FALSE,
           label_leaves = FALSE,
           group_label_size = 5) +
        scale_color_manual(values = c('red', 'blue', 'green', 'maroon', 'yellow', 'cyan'))


# ...4. Order the cells in pseudotime -------------------

cds <- order_cells(cds, reduction_method = "UMAP", root_pr_nodes = get_earliest_principal_node(cds, time_bin = "Naive_like_3"))

p2 <- plot_cells(cds,
                color_cells_by = 'pseudotime',
                label_groups_by_cluster = FALSE,
                label_branch_points = FALSE,
                label_roots = FALSE,
                label_leaves = FALSE) +
  theme_lisa() +
  theme(legend.key.size = unit(0.25, 'cm'))
ggsave(filename = paste0("~/Desktop/Trajectory_stim_reduced_pseudotime.pdf"), plot = p2, width = 3, height = 2)
p1 | p2
```
```{r}
sessionInfo()
```
